<?php

namespace Mant\AlmacenBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlmacenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlmacenRepository extends EntityRepository
{
    
    public function findAlmacenesActivas()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM MantAlmacenBundle:Almacen a WHERE a.activa = :activa ORDER BY a.nombre'
            )
            ->setParameter('activa', true)
            ->getResult();
    }
}
