<?php

namespace Mant\AlmacenBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Mant\AlmacenBundle\Entity\Articulo;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{



}
