<?php

namespace Mant\AlmacenBundle\Entity\gestion;

use Doctrine\ORM\EntityRepository;

/**
 * EstructuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstructuraRepository extends EntityRepository
{
}
