<?php

namespace Mant\AlmacenBundle\Entity\gestion;

use Doctrine\ORM\EntityRepository;

/**
 * UnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnidadRepository extends EntityRepository
{
}
