<?php

namespace GestionUsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoleUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleUsuarioRepository extends EntityRepository
{
}
