<?php

namespace GestionUsuariosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function getAllUser()
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT u
                                   FROM GestionUsuariosBundle:Usuario u
                                   ORDER BY u.apellido'
                    )
                    ->getResult();
    }     
}
