<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\EntityRepository;

/**
 * ConceptoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoMovimientoRepository extends EntityRepository
{
    
    public function getConceptoAsociado($movimiento)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM MantAlmacenBundle:movimientos\ConceptoMovimiento m WHERE m.movAfectado = :movimiento'
            )
            ->setParameter('movimiento', $movimiento->getTipoFormulario())
            ->getOneOrNullResult();
    }      
}