<?php

namespace Mant\AlmacenBundle\Entity\movimientos;

use Doctrine\ORM\EntityRepository;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends EntityRepository
{
    public function findMovimientosPendientesIngresar($deposito)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT p FROM MantAlmacenBundle:movimientos\Proveedor p WHERE p.deposito = :deposito ORDER BY p.razonSocial')
                    ->setParameter('deposito', true)
                    ->getResult();
    }    
}
