<?php

namespace Mant\AlmacenBundle\Entity\finanzas;

use Doctrine\ORM\EntityRepository;

/**
 * FacturaProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaProveedorRepository extends EntityRepository
{
    
    public function findFacturasProveedorPendientes($deposito)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT fp 
                           FROM MantAlmacenBundle:finanzas\FacturaProveedor fp 
                           WHERE fp.almacen = :almacen AND fp.procesada = :procesada'
            )
            ->setParameter('almacen', $deposito)           
            ->setParameter('procesada', false)                
            ->getResult();
    }       
}
